# working_directory = 'x:\CampioneProjects'

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 9.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "pwsh"

[window]
# decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.975
# padding = { x = 5, y = 5 }

[window.dimensions]
columns = 132
lines = 43

[general]
live_config_reload = true

[terminal]
